api_platform:
    title: 'Exercice CRUD / API Platform'
    description: 'Une API pour comprendre le fonctionnement des Apis avec symfony'
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        html: ['text/html']
        multipart: ['multipart/form-data']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
