vich_uploader:
    db_driver: orm

#    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    mappings:
        post_image:
            uri_prefix: /images/stagiaires
            upload_destination: '%kernel.project_dir%/public/images/stagiaires'